baseURL = "/"
languageCode = "ru-ru"
title = "UI8Kit Hugo Site"
paginate = 10

[params]
  description = "Static site powered by Hugo"
  author = "buildy"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


